# Generated by Django 4.2.6 on 2023-11-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen_Producto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
