# Generated by Django 4.2.6 on 2023-11-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_productos_imagen_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen_Producto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
