# Generated by Django 4.2.6 on 2023-11-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_productos_imagen_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
